// Code generated by "stringer -type Alignment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAST-1]
	_ = x[WEST - -1]
}

const (
	_Alignment_name_0 = "WEST"
	_Alignment_name_1 = "EAST"
)

func (i Alignment) String() string {
	switch {
	case i == -1:
		return _Alignment_name_0
	case i == 1:
		return _Alignment_name_1
	default:
		return "Alignment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
