// Code generated by "stringer -type CreatureColor"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_COLOR-0]
	_ = x[Red-1]
	_ = x[Green-2]
	_ = x[Blue-3]
}

const _CreatureColor_name = "NO_COLORRedGreenBlue"

var _CreatureColor_index = [...]uint8{0, 8, 11, 16, 20}

func (i CreatureColor) String() string {
	if i < 0 || i >= CreatureColor(len(_CreatureColor_index)-1) {
		return "CreatureColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CreatureColor_name[_CreatureColor_index[i]:_CreatureColor_index[i+1]]
}
