// Code generated by "stringer -type Species"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_SPECIES-0]
	_ = x[Duck-1]
	_ = x[Tortoise-2]
	_ = x[Capybara-3]
}

const _Species_name = "NO_SPECIESDuckTortoiseCapybara"

var _Species_index = [...]uint8{0, 10, 14, 22, 30}

func (i Species) String() string {
	if i < 0 || i >= Species(len(_Species_index)-1) {
		return "Species(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Species_name[_Species_index[i]:_Species_index[i+1]]
}
